[tool.poetry]
name = "brainles_preprocessing"
version = "0.0.5"
description = "TODO."
authors = [
  "Florian Kofler <florian.kofler@tum.de>",
  "Isra Mekki <isra.mekki@helmholtz-muenchen.de>",
]
license = "AGPL-3.0"

[tool.poetry.dependencies]
python = ">=3.10"
# core
path = ">=16.2.0"
ttictoc = ">=0.5.6"
pathlib = ">=1.0.1"
nibabel = ">=3.2.1"
numpy = ">=1.23.0"

# hd-bet reqs
BrainLes-HD-BET = ">=0.0.5"

# utils
tqdm = ">=4.64.1"
auxiliary = ">=0.0.35"
# TODO add citation dependency

[tool.poetry.dev-dependencies]
pytest = "^6.2"
